server:
  port: # 端口

spring:
  main:
    allow-circular-references: true  # 项目代码存在引用环, 强制允许了, 后续进行修改

  # 数据库配置
  datasource:
    druid:
      driver-class-name:
      url:
      username:
      password:
      min-idle:
      max-active:

  # redis 配置
  redis:
    host:
    port:
    password:
    database:
    lettuce:
      pool:
        max-active:
        max-idle:
        min-idle:
        max-wait:

  # 默认允许的文件大小太小
  servlet:
    multipart:
      max-file-size:
      max-request-size:

# mp 日志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# 日志打印
logging:
  charset:
    file:
  file:
    path:
  pattern:
    console:
    file:

# 项目的其他配置
homework-helper:
  # token 的盐
  token:
    secret:

  # 腾讯 sms 短信的配置信息
  sms:
    secret-id:
    secret-key:
    region:
    sdk-app-id:
    sign-name:
    template-id:
    country-code:
    code-key-prefix:

  # 阿里云 oss 存储的配置信息
  oss:
    endpoint:
    access-key-id:
    accesskey-secret:
    bucket-name:
    base-path:

  # 登录保存密码的盐
  login:
    secret:
